// code types
const UPDATE_CODE = 'UPDATE_CODE';

const CODE = {UPDATE_CODE};


// settings type
const FONT_SIZE = 'FONT_SIZE';
const TAB_SIZE = 'TAB_SIZE';
const WRAP_LINE = 'WRAP_LINE';
const ADD_LIBRARIES = 'ADD_LIBRARIES';
const REMOVE_LIBRARIES = 'REMOVE_LIBRARIES';
const UPDATE_LOAD_LIBRARY_FLAG = 'UPDATE_LOAD_LIBRARY_FLAG';

const SETTINGS = {
    FONT_SIZE, 
    TAB_SIZE, 
    WRAP_LINE, 
    ADD_LIBRARIES, 
    REMOVE_LIBRARIES, 
    UPDATE_LOAD_LIBRARY_FLAG
}

export {CODE, SETTINGS};